// flow-typed signature: a2bf184682c2a3540e8fc881488fe767
// flow-typed version: <<STUB>>/barterdex-api_vfile:../barterdex-api/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'barterdex-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'barterdex-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'barterdex-api/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'barterdex-api/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'barterdex-api/jest.config' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/add-server' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/balance' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/buy' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/get-endpoint' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/getfee' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/http-provider' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/index' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/is-ready' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/list-transactions' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/listunspent' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/login' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/orderbook' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/recentswaps' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/schema' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/send-raw-transaction' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/swapstatus' {
  declare module.exports: any;
}

declare module 'barterdex-api/lib/withdraw' {
  declare module.exports: any;
}

// Filename aliases
declare module 'barterdex-api/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'barterdex-api/coverage/lcov-report/prettify'>;
}
declare module 'barterdex-api/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'barterdex-api/coverage/lcov-report/sorter'>;
}
declare module 'barterdex-api/jest.config.js' {
  declare module.exports: $Exports<'barterdex-api/jest.config'>;
}
declare module 'barterdex-api/lib/add-server.js' {
  declare module.exports: $Exports<'barterdex-api/lib/add-server'>;
}
declare module 'barterdex-api/lib/balance.js' {
  declare module.exports: $Exports<'barterdex-api/lib/balance'>;
}
declare module 'barterdex-api/lib/buy.js' {
  declare module.exports: $Exports<'barterdex-api/lib/buy'>;
}
declare module 'barterdex-api/lib/get-endpoint.js' {
  declare module.exports: $Exports<'barterdex-api/lib/get-endpoint'>;
}
declare module 'barterdex-api/lib/getfee.js' {
  declare module.exports: $Exports<'barterdex-api/lib/getfee'>;
}
declare module 'barterdex-api/lib/http-provider.js' {
  declare module.exports: $Exports<'barterdex-api/lib/http-provider'>;
}
declare module 'barterdex-api/lib/index.js' {
  declare module.exports: $Exports<'barterdex-api/lib/index'>;
}
declare module 'barterdex-api/lib/is-ready.js' {
  declare module.exports: $Exports<'barterdex-api/lib/is-ready'>;
}
declare module 'barterdex-api/lib/list-transactions.js' {
  declare module.exports: $Exports<'barterdex-api/lib/list-transactions'>;
}
declare module 'barterdex-api/lib/listunspent.js' {
  declare module.exports: $Exports<'barterdex-api/lib/listunspent'>;
}
declare module 'barterdex-api/lib/login.js' {
  declare module.exports: $Exports<'barterdex-api/lib/login'>;
}
declare module 'barterdex-api/lib/orderbook.js' {
  declare module.exports: $Exports<'barterdex-api/lib/orderbook'>;
}
declare module 'barterdex-api/lib/recentswaps.js' {
  declare module.exports: $Exports<'barterdex-api/lib/recentswaps'>;
}
declare module 'barterdex-api/lib/schema.js' {
  declare module.exports: $Exports<'barterdex-api/lib/schema'>;
}
declare module 'barterdex-api/lib/send-raw-transaction.js' {
  declare module.exports: $Exports<'barterdex-api/lib/send-raw-transaction'>;
}
declare module 'barterdex-api/lib/swapstatus.js' {
  declare module.exports: $Exports<'barterdex-api/lib/swapstatus'>;
}
declare module 'barterdex-api/lib/withdraw.js' {
  declare module.exports: $Exports<'barterdex-api/lib/withdraw'>;
}
