// flow-typed signature: c85d595d171e96da71a4a13ac09732c2
// flow-typed version: <<STUB>>/barterdex-utilities_vfile:../barterdex-utilities/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'barterdex-utilities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'barterdex-utilities' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'barterdex-utilities/jest.config' {
  declare module.exports: any;
}

declare module 'barterdex-utilities/lib/dateFormat' {
  declare module.exports: any;
}

declare module 'barterdex-utilities/lib/dotProp' {
  declare module.exports: any;
}

declare module 'barterdex-utilities/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'barterdex-utilities/jest.config.js' {
  declare module.exports: $Exports<'barterdex-utilities/jest.config'>;
}
declare module 'barterdex-utilities/lib/dateFormat.js' {
  declare module.exports: $Exports<'barterdex-utilities/lib/dateFormat'>;
}
declare module 'barterdex-utilities/lib/dotProp.js' {
  declare module.exports: $Exports<'barterdex-utilities/lib/dotProp'>;
}
declare module 'barterdex-utilities/lib/index.js' {
  declare module.exports: $Exports<'barterdex-utilities/lib/index'>;
}
