// flow-typed signature: 5f74d86ee967f07eb875f90ee2c0b4c4
// flow-typed version: <<STUB>>/barterdex-rssm_vfile:../barterdex-rssm/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'barterdex-rssm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'barterdex-rssm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'barterdex-rssm/jest.config' {
  declare module.exports: any;
}

declare module 'barterdex-rssm/lib/index' {
  declare module.exports: any;
}

declare module 'barterdex-rssm/lib/takeFirst' {
  declare module.exports: any;
}

// Filename aliases
declare module 'barterdex-rssm/jest.config.js' {
  declare module.exports: $Exports<'barterdex-rssm/jest.config'>;
}
declare module 'barterdex-rssm/lib/index.js' {
  declare module.exports: $Exports<'barterdex-rssm/lib/index'>;
}
declare module 'barterdex-rssm/lib/takeFirst.js' {
  declare module.exports: $Exports<'barterdex-rssm/lib/takeFirst'>;
}
