// flow-typed signature: 2ab94616311f58894401135b3b560448
// flow-typed version: <<STUB>>/barterdex-components_vfile:../barterdex-components/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'barterdex-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'barterdex-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'barterdex-components/__tests__/barterdex-components.test' {
  declare module.exports: any;
}

declare module 'barterdex-components/lib/Header' {
  declare module.exports: any;
}

declare module 'barterdex-components/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'barterdex-components/__tests__/barterdex-components.test.js' {
  declare module.exports: $Exports<'barterdex-components/__tests__/barterdex-components.test'>;
}
declare module 'barterdex-components/lib/Header.js' {
  declare module.exports: $Exports<'barterdex-components/lib/Header'>;
}
declare module 'barterdex-components/lib/index.js' {
  declare module.exports: $Exports<'barterdex-components/lib/index'>;
}
