// flow-typed signature: 3747669a369b3fe24dda5704b53aeb4b
// flow-typed version: <<STUB>>/electron-util_v^0.10.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-util/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-util/index' {
  declare module.exports: $Exports<'electron-util'>;
}
declare module 'electron-util/index.js' {
  declare module.exports: $Exports<'electron-util'>;
}
declare module 'electron-util/node.js' {
  declare module.exports: $Exports<'electron-util/node'>;
}
