// flow-typed signature: 8612dc155bd78af322b5f2bc9c183b45
// flow-typed version: <<STUB>>/react-memoize_v^1.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-memoize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-memoize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-memoize/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-memoize/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-memoize/dist/Context' {
  declare module.exports: any;
}

declare module 'react-memoize/dist/index' {
  declare module.exports: any;
}

declare module 'react-memoize/dist/MemoizedRender' {
  declare module.exports: any;
}

declare module 'react-memoize/dist/Memoizer' {
  declare module.exports: any;
}

declare module 'react-memoize/dist/Waterflow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-memoize/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-memoize/coverage/lcov-report/prettify'>;
}
declare module 'react-memoize/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-memoize/coverage/lcov-report/sorter'>;
}
declare module 'react-memoize/dist/Context.js' {
  declare module.exports: $Exports<'react-memoize/dist/Context'>;
}
declare module 'react-memoize/dist/index.js' {
  declare module.exports: $Exports<'react-memoize/dist/index'>;
}
declare module 'react-memoize/dist/MemoizedRender.js' {
  declare module.exports: $Exports<'react-memoize/dist/MemoizedRender'>;
}
declare module 'react-memoize/dist/Memoizer.js' {
  declare module.exports: $Exports<'react-memoize/dist/Memoizer'>;
}
declare module 'react-memoize/dist/Waterflow.js' {
  declare module.exports: $Exports<'react-memoize/dist/Waterflow'>;
}
